sourcegraph/codeintellify

- src/token_position.test.ts
- src/token_position.ts
This PR fixes an issue where only portions of a token can be highlighted. This can happen any time a token spans multiple elements but mostly happens in diffs when just part of a variable name was changed. The resulting DOM can look like this: `my<span>Token</span>`. If you hover over `my` without these changes, only `my` will be highlighted and same for `Token`. 
These changes walk backwards and forwards in the list of text nodes ensuring we get the full token.
> fix: getTokenAtPositon gets the full token, even when it spans elements

- src/hoverifier.ts
- src/token_position.test.ts
- src/token_position.ts
This PR fixes two closely related issues
1. @chrismwendt asked if it were possible for the `commonAncestorContainer` to be too high up in the tree and I, incorrectly, assumed that it couldn't. This PR fixes that.
2. The previous PR fixed the problem where we highlight only part of a token by refactoring `getTokenAtPosition`. We still had a problem with placing the tooltip because the event targets weren't guaranteed to be the full token so we use `getTokenAtPosition` to correct that.
> Get full token fix

- src/hoverifier.test.ts
- src/hoverifier.ts
The python language server responds with contents but not a range sometimes. This means that we can end up with tooltip data and the tooltip displayed but no token highlighting. This PR rearranges some stuff to more robustly handle this and still adjust the position each time if necessary.
> fix: correct position adjusting observable usage

- src/hoverifier.ts
Before https://github.com/sourcegraph/codeintellify/pull/45, we didn't highlight the hovered token until we got a hover response. Otherwise we'd highlight _every single_ token including whitespace and comments even if there's no hover information. This PR fixes that regression while keeping the improvements from #45 .
> fix: Highlight only when response

- src/hoverifier.ts
Sometimes language servers return invalid hover information. Currently, codeintellify just sort of gets angry and quits working after this happens. @chrismwendt and I discussed a few different options for handling this and we decided that while the solution this PR has is the ideal solution<sup>1</sup>, it is more convenient for consumers of codeintellify. 
<sup>1</sup> The ideal solution would be that each language server perfectly adheres to the specification or at least _each_ codeintellify consumer handles the errors on it's own.
> fix: handle invalid hover responses by displaying errors

- package-lock.json
- src/hoverifier.ts
- src/positions.ts
Updates to RxJS 6.3, which includes my PR that fixes the `Subscribable` signature.
We can replace all required _inputs_ that were `Observable` before with `Subscribable` (and convert them with `from()`) so that we depend on interfaces instead of classes. Interfaces are duck-typed, so `npm link`ed versions don't cause conflicts if the interfaces are compatible.
All callback types can now return `SubscribableOrPromise` to make clear that they should only return one result. Eventually I would like to switch them to return only `Promise` and pass an `AbortSignal` (but it would be a breaking change).
> Accept Subscribable

- src/token_position.test.ts
- src/token_position.ts
Closes https://github.com/sourcegraph/codeintellify/issues/54.
I guess this answers [this question](https://github.com/sourcegraph/codeintellify/pull/41#discussion_r210337115).
> Convert node changes text

- src/helpers.ts
- src/hoverifier.ts
Sending `null` and `{content: []}` are both valid responses from language servers for empty hover responses. Before this PR, if we got `{content: []}`, we highlight the token because it is a valid hover, however, this is not the intended experience.
Fixes https://github.com/sourcegraph/sourcegraph/issues/13180
> fix: don't highlight on empty hover responses

- README.md
- src/HoverOverlay.tsx
- src/url.ts
It is rarely supported and used, so it does not deserve such prominent billing. A future commit will allow consumers to add this button back.
Helps with https://github.com/sourcegraph/sourcegraph/issues/492
> feat: remove Find Implementations button

- src/HoverOverlay.tsx
- src/hoverifier.test.ts
- src/hoverifier.ts
This is in preparation for removing the hard-coded actions from this library and letting the consumer provide its own actions. This change simplifies the code (slightly) in advance of that.
> feat: remove telemetry event logging

- src/HoverOverlay.scss
Per @francisschmaltz's comment https://github.com/sourcegraph/codeintellify/pull/73#issuecomment-445906578
This reverts commit #73 because it was not in line with padding elsewhere in our app. The previous padding was a good amount and matched the rest of our app.
Keeps the `:last-child` change.
> Revert "feat: less spacing in HoverOverlay SCSS"

- src/hoverifier.test.ts
- src/hoverifier.ts
- src/positions.ts
Fixes an issue where the TOOLTIP_DISPLAY_DELAY behavior (not showing the tooltip until the mouse had stopped moving for 100msec) was ineffective because no mousemove events were being received. This was because there was no mousemove event listener.
Test plan:
1. Before applying this fix, move your mouse quickly over a token without stopping for 100msec. (You can increase the TOOLTIP_DISPLAY_DELAY constant to make this easier.) Notice that the tooltip appears despite your mouse not ever being stopped for any period of 100msec.
2. Apply this fix. Now try the same. Notice that the tooltip does not appear until your mouse stops moving for 100msec.
> fix: listen for mousemove events (previously was not listening)

- src/helpers.ts
- src/hoverifier.test.ts
- src/hoverifier.ts
Fixes an issue where the token would be highlighted before the hover was shown or finished loading (if the hover was taking a while to load). The goal of this change is to avoid UI jitter: it makes sense to not show any changes in the UI (including highlighting the hovered range) until we know they will not need to be immediately redrawn.
If the token is highlighted and then a few hundred msec later the hover is determined to be empty, the highlight will go away. That looks jittery, and that problem is fixed by this commit.
(This commit also makes codeintellify consistent with VS Code's behavior. The VS Code "Loading..." hover does not result in the underlying token being highlighted. Try it by running the "Reload Window" action in VS Code and immediately hovering a token.)
> fix: delay highlighting the hovered token until the hover is shown

- src/HoverOverlay.scss
The close button obscures the hover content or actions. As a partial fix, this commit makes it so that the close button only appears when the overlay is hovered, so that it is possible to read all of the content.
Replaces #77
> feat: only show close button on pinned overlays on hover

- src/hoverifier.test.ts
- src/hoverifier.ts
If the overlay is visible due to a mouseover event and the user clicks a token to pin it, previously the overlay would briefly disappear as its data was reloaded. This could be worked around in the consumer by having replayable observables, but most consumers did not implement this correctly. Now, when a click event pins the overlay (and does not change its position from what the prior mouseover event yielded), it does not unsubscribe the previous data observables; it remains visible and subscribed.
> fix: overlay remains visible on click when already moused over

- src/hoverifier.test.ts
- src/hoverifier.ts
Fix https://github.com/sourcegraph/sourcegraph/issues/1417.
The hover result was not being properly translated from 0-indexed to 1-indexed.
> fix: off-by-one hover range result

- src/helpers.ts
The markdown is passed to [marked](https://marked.js.org/) and then to [sanitize-html](https://www.npmjs.com/package/sanitize-html). In order to get the needed tags, I put my needed markdown into [marked's demo](https://marked.js.org/demo) and looked at the HTML they provided.
> Add allowed tags and attributes for extensions

- src/hoverifier.ts
Previously, `getActions()` was being called multiple times (triggering multiple `$observeDefinition`s) for the same position because `actionObservables` is subscribed to twice.
This shares the result of `getActions()` across subscriptions.
Fixes https://github.com/sourcegraph/sourcegraph/issues/1321
> fix: avoid calling getActions multiple times

- karma.conf.ts
- src/hoverifier.test.ts
- src/hoverifier.ts
Fixes #99 
Fixes https://github.com/sourcegraph/sourcegraph/issues/1064
Proper fix for workaround in https://github.com/sourcegraph/sourcegraph/pull/1171
Ref https://github.com/sourcegraph/sourcegraph/issues/750
> fix: hide the overlay on hoverify unsubscription

- README.md
- src/hoverifier.test.ts
- src/hoverifier.ts
Continuation of #100 
The code view was still possible to be re-shown after being hidden because the nested action and hover Observables were not unsubscribed from and could emit after the code view was unhoverified. This would happen on a page navigation, because the removed code view causes the text documents in the extension API to be updated, which causes the Observable returned by `getActions` to emit again.
The test reproduces the problem by making `getActions` emit something.
The fix is to use `takeUntil()` to only take from the actions and hover Observables until the code view is unsubscribed (we need to do this for the two higher-order Observables).
Fixes https://github.com/sourcegraph/sourcegraph/issues/3108
> fix: unsubscribe from actions and hover observable

- src/hoverifier.test.ts
- src/hoverifier.ts
- src/testutils/fixtures.ts
This will let Sourcegraph provide single-click jump-to-definition behavior:
Subsumes https://github.com/sourcegraph/codeintellify/pull/42 cc @dadlerj just FYI
> Expose the currently hovered token and support disabling pinning

- renovate.json
This prevents minor updates.
Use the inherited "bump" strategy.
> chore: don't use replace for devDependencies

- src/hoverifier.test.ts
- src/positions.test.ts
- src/positions.ts
Motivation: some code hosts have already tokenized the code view (e.g. Bitbucket). The tokenization currently prevents text selection from working on Bitbucket https://github.com/sourcegraph/sourcegraph/issues/4051
Implementation: this lets callers specify a boolean `tokenize` to control whether or not tokenization occurs.
Slack conversation https://sourcegraph.slack.com/archives/CHXHX7XAS/p1559599129008000
> feat: conditionally tokenize cells

- src/hoverifier.ts
- src/token_position.test.ts
- src/token_position.ts
In #115 I forgot a few code paths where `convertNode()` gets called.
This adds a `tokenize` property to `createHoverifier` and plumbs it through a few of the token-finding functions.
> Conditionally tokenize code views (continued)

- src/hoverifier.ts
Previously only `null` was considered empty. This caused pinned hovers that could not be unpinned (cause they were invisible/not rendered).
Fixes https://github.com/sourcegraph/sourcegraph/issues/4940
Alternative to https://github.com/sourcegraph/sourcegraph/pull/4941
> Unpin hover if actions come back as empty array

- src/helpers.ts
- src/hoverifier.test.ts
- src/hoverifier.ts
- testdata/github/generate.ts
- testdata/github/styles.css
Rel  [RFC 76](https://docs.google.com/document/d/1albi6HaAU9JAqdQXjsE-50NidxG4icE-36XqxxKgfM4/edit)
Introduces `HoverifyOptions.scrollBoundaries`, an array of `HTMLElement`, which would typically contain elements with a lower z-index than the hover overlay but a higher z-index than the code view, such as a sticky file header.
At runtime, in reaction to scroll events, hide the hover overlay when it overlaps with a hover boundary.
`IntersectionObserver` could not be used here, as it requires an ancestor relationship between the root and target elements.
**Before**:
<details>
</details>
**After**:
<details>
</details>
> feat: add HoverifyOptions.scrollBoundaries

- package.json
- src/errors.ts
- src/hoverifier.test.ts
- src/hoverifier.ts
- src/overlay_position.test.ts
- src/testutils/dom.ts
- src/testutils/fixtures.ts
- src/token_position.test.ts
- src/token_position.ts
- yarn.lock
- Use nullish coalescing, prefer readonly, and other TypeScript eslint fixes
- Upgrade TypeScript to a version that definitely supports these new features
> chore: upgrade TypeScript and modernize practices

- src/errors.ts
Errors in ECMAScript have a `message` and a `name`. `code` is something Node-specific, and those errors still all have `name`. Native errors like `TypeError`, `URIError`, `AggregateError` (coming soon) all only have `name`. When we send errors to/from background pages or web workers, we can only reasonably expect `name` to be present, so we should never rely on `code`. See e.g. https://github.com/mozilla/webextension-polyfill/issues/210 or `comlink` source code.
Using both in our codebase inconsistently opens the risk to checking for the wrong property, (especially because errors are `any` in TypeScript) and adds additional code.
This change removes all uses of `code` in favor of `name`. There is still a case for having `name` be optional (e.g. GraphQL errors don't have a `name`, but do …
> fix: use error names, not error codes

- src/hoverifier.ts
As discussed in the web sync and in https://docs.google.com/document/d/1TPTH33vOVXqhKgVEeohnZh1sZA02M_hfZVx0YBvX5QI/edit
> feat: reduce LOADER_DELAY to 600

- package.json
- src/helpers.ts
- src/hoverifier.test.ts
- src/hoverifier.ts
- src/index.ts
- src/loading.test.ts
- src/loading.ts
- src/testutils/fixtures.ts
- src/types.ts
- webpack.test.config.ts
- yarn.lock
This addresses https://github.com/sourcegraph/sourcegraph/issues/9349, https://github.com/sourcegraph/sourcegraph/issues/9350 and https://github.com/sourcegraph/sourcegraph/issues/9346.
Codeintellify was originally not written to support providers updating the hover content later. It accepted Observables for cancellation, but they were intended to only emit once.
With extensions, Observables started to emit multiple times to update the content. The problem is that the period between invocation and the first result is used to display a loading indicator. But with multiple emissions, the situation can arise where first an empty result is emitted (e.g. because no providers were registered yet), then providers get registered and start loading, then emit actual non-empty result. Codeintellify …
> feat: allow hover providers to communicate loading state

- src/hoverifier.test.ts
- src/hoverifier.ts
- src/testutils/fixtures.ts
- src/types.ts
Part of https://github.com/sourcegraph/sourcegraph/issues/10868. Sibling PRs: https://github.com/sourcegraph/sourcegraph/pull/11822 and https://github.com/sourcegraph/code-intel-extensions/pull/409
This PR adds functionality to subscribe to hover events and highlight the ranges which are returned from the new `createHoverifier` parameter of `createHoverifier`. This is conceptually symmetric to what happens when the hover symbol itself is highlighted.
> feat: document highlights

- src/hoverifier.ts
- src/token_position.test.ts
- src/token_position.ts
Closes #224
Find and highlight tokens by range, not just position.
Limitations:
- `start` and `end` position must be on the same line
- Highlight class will be applied to all elements within the range
> feat: support highlighting tokens by range

- src/token_position.test.ts
- src/token_position.ts
Fix error discussed in #360, introduced by #331.
Treat end position of a range as exclusive. Previously, we would erroneously highlight DOM nodes that started at hovered nodes' specified end positions.
> fix: exclude end position in findElementWithOffset

- src/hoverifier.ts
- src/token_position.ts
Some code hosts use many types of code views, some of which are tokenized and some of which are not. This PR introduces a way for consumers to override the `Hoverifier` instance `tokenize` flag through event options in `Hoverifer#hoverify`.
> feat: add code view-specific tokenization settings

- src/hoverifier.test.ts
- src/hoverifier.ts
Resolves https://github.com/sourcegraph/codeintellify/issues/48
> feat: delay hiding the overlay
